version: "3"
services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
      target: dev
    volumes:
      - ./src:/go/src
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "${APP_PORT:-8080}:8080"
    env_file:
      - ./.env
    command: air -c .air.toml

  perl:
    build:
      context: .
      dockerfile: ./docker/perl/Dockerfile
    container_name: go-play-langs-perl
    volumes:
      - ./src/share/scripts:/user/scripts
    tty: true
